### ISSUE TITLE
Käyttäjän kirjautumisen pystyy toteuttamaan käyttöliittymässä.

### ISSUE THREAD

**Issue by riikkayoki** [Anturit/Anturidatan_visualisointi#25]
Task liittyen käyttäjätarinaan: **[Käyttäjä voi kirjautua sovellukseen](https://github.com/Anturit/Anturidatan_visualisointi/issues/18)**

**Comment by elonheimo** [comment]
Ei testejä

**Comment by elonheimo** [comment]
Lisätty logout,
Ei edelleen testejä

**Comment by riikkayoki** [comment]
Moi tehdään tästä logoutista erillinen task
