### ISSUE TITLE
Automaattiset e2e-testit 6h välein tuotantoversiolle

### ISSUE THREAD

**Issue by hnenonen** [Anturit/Anturidatan_visualisointi#340]
6h välein automaattisesti ajettavat e2e-testit eri selaimille CI-pipelinessa, koska tuotantoversio voi hajota välissä esim. johtuen selaimen versiopäivityksestä

**Comment by elonheimo** [comment]
Pyörii kerran vuorokaudessa aamuyöllä.
Ja kyse ei ole tuotantoversiosta vaan siitä mikä on github repon mainissa.
